server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Logs vão para stdout/stderr para o CloudWatch Logs capturar
    access_log /dev/stdout;
    error_log  /dev/stderr;

    root /var/www/html;
    index index.php;

    server_name _;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}
