[www]
user = www-data
group = www-data

listen = 127.0.0.1:9000

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; ESSENCIAL: permite que variáveis de ambiente do container
; cheguem até o getenv() do PHP (DB_HOST, DB_USER, DB_PASS, DB_NAME)
clear_env = no